### PR TITLE
Tweaks to maps

### LINKED ISSUE #128: Roboticists have no access to First Aid Stations
#### Brief description of the issue
I got shocked by an autolathe and lost a hand. Tried to crawl to the First Aid Station( no medical doctors online) and when I tried to open the airlock, it beeped, showing that i have no access to it. For some reason engineers and cargo techs don't have that problem at all.

#### What you expected to happen
Airlock opening

#### What actually happened
Airlock beeping(aka access denied)

#### Steps to reproduce
- Be a roboticist
- Get hurt
- Crawl to First Aid
- Access denied
- Die

#### Code Revision
- master - 2018-12-13
142bdd50ab91872967d65aedbeb91365a5687ea4 
 
#### Anything else you may wish to add:
- The First Aid Station over the Security Checkpoint

### LINKED ISSUE #182: Security lobby isn't public access
#### Brief description of the issue
The part of the security department (the lobby, which each department has publicly available) is inaccessible to non-security. Even some heads can't access it. It shouldn't even check for access.

#### What you expected to happen
For people to be able to go into the security lobby where there's chairs and a front desk and a second set of locked doors.

#### What actually happened
You can't.

#### Code Revision
- 78d1e112dd333d9a8fce745885919daa939575bb

### LINKED ISSUE #183: The main outpost's doors to medical and security rooms have inconsistent access
#### Brief description of the issue
The doors leading from the gateway chamber into the security, explorer and medical sections are access-restricted, but the clear glass airlocks just a few tiles south leading into the same sections are not.

#### What you expected to happen
For the access to be consistent, one way or the other. Either the doors *all* need to be access-restricted, or none of them should be.

#### What actually happened
Read above.

#### Code Revision
- 78d1e112dd333d9a8fce745885919daa939575bb 
 
#### Anything else you may wish to add:
dreamseeker_2019-04-06_02-23-21

### LINKED ISSUE #186: Mapping oversights- Missing items from the code
#### Brief description of the issue
Certain things are missing from the Northern Star map that the code we're on uses. Certain items like biomass for the cloning machine, the Sleeve-Mate, and the body design console disk.

#### What you expected to happen
The map to be adapted to the codebase.

#### What actually happened
Some key items from the codebase are missing from the map still.

#### Steps to reproduce
- (Step 1) Look around and think for a moment.
- (Step 2) Notice that some key items are missing.

#### Code Revision
master - 2019-04-03
- 78d1e112dd333d9a8fce745885919daa939575bb
 
#### Anything else you may wish to add:

-Station medbay cloning room traditionally had a couple bottles of 'Biomass'. It currently does not have this. Biomass can still be made in chemistry.
-There are no Sleeve-Mates in the station medbay. This was an alternative to the backup implanter. I believe there was typically one in cloning, one in medbay equipment, and one in secondary storage.
-Cloning room at the central command z-level has meat instead of biomass. Meat doesn't work on this codebase anymore. Since this cloning room doesn't start with any biomass, it can't be used unless some is produced from the nearby chemistry room.
-The 'body design console' was placed in the lobby of medbay, but there are no disks for it. As such, no bodies can be produced with it. It uses a special 'body design disk' that cannot be produced by science or ordered by cargo. There was traditionally a box of these disks behind the front desk in medbay.

### PR DESCRIPTION
**Pull request by EvilJackCarver**
**Developer's note:** southern_cross_3.dmm's diff file is large because of MapMerge1. If necessary, I can go and redo the tweaks in FastDMM, and resubmit without running it through the merger.

:cl: EvilJackCarver
rscadd: Medical now has biomass in the chemistry lab, near the phoron.
rscadd: A Sleevemate has been added to the resleeving lab, on the table by the limb printer.
bugfix: Centcomm Cloning now has biomass, instead of synthmeat.
bugfix: Outpost Medical (SAR Prep) and Security doors now have consistent access. Players can now no longer enter the area without appropriate access. Outpost Explorer Prep maintains its previous access state, as the exit is there.
tweak: Security Lobby doors are now all-access. The doors have been repainted to reflect this.
tweak: Removes required-all access of 63 (Security Generic) from brig foyer doors, and adds it to the required-one access list.
tweak: First Aid Stations no longer have access requirements.
rscdel: Removes body design console. There is now a shrubbery there.
/:cl:

CLOSES #128 AS FIXED
CLOSES #182 AS FIXED
CLOSES #183 AS FIXED
CLOSES #186 AS FIXED

### CODE REVIEW

**Comment by EvilJackCarver** [comment]
Don't-merge: I missed a mapping-related issue. I'll go ahead and get that fixed.

**Comment by EvilJackCarver** [comment]
Fix for PR #128 pushed. I was able to open it after putting my ID in my backpack. Just waiting on Travis.

**Comment by drexample** [comment]
Sorry to notify you this late, but staff decided on removing body design console from the medbay entirely. 
Could you do that, please?

**Comment by EvilJackCarver** [comment]
Done. I replaced it with a shrubbery so it doesn't look so empty.

image

**Pull request merged**
